//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedRentalView
    {
        public int itemRentalId { get; set; }
        public int stockId { get; set; }
        public string itemName { get; set; }
        public int memberId { get; set; }
        public string memberName { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public int zip { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> rentalDateTime { get; set; }
        public Nullable<int> shipEmployeeId { get; set; }
        public Nullable<System.DateTime> shipDateTime { get; set; }
        public Nullable<int> returnEmployeeId { get; set; }
        public Nullable<System.DateTime> returnDateTime { get; set; }
        public string returnCondition { get; set; }
        public string shippedCondition { get; set; }
    }
}
