//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemReturn
    {
        public int itemReturnId { get; set; }
        public int memberId { get; set; }
        public int stockId { get; set; }
        public int employeeId { get; set; }
        public string itemCondition { get; set; }
        public string description { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Member Member { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
