//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemShip
    {
        public int itemShipId { get; set; }
        public int employeeId { get; set; }
        public int itemRentalId { get; set; }
        public string itemCondition { get; set; }
        public string itemDescription { get; set; }
        public System.DateTime shipDateTime { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ItemRental ItemRental { get; set; }
    }
}
