//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRental
    {
        public int itemRentalId { get; set; }
        public int stockId { get; set; }
        public int memberId { get; set; }
        public int addressId { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> rentalDateTime { get; set; }
        public Nullable<int> shipEmployeeId { get; set; }
        public Nullable<System.DateTime> shipDateTime { get; set; }
        public Nullable<int> returnEmployeeId { get; set; }
        public Nullable<System.DateTime> returnDateTime { get; set; }
        public string returnCondition { get; set; }
        public Nullable<System.DateTime> dueDateTime { get; set; }
        public string shippedCondition { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Member Member { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
