//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDetailView
    {
        public int stockId { get; set; }
        public int productId { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public string productType { get; set; }
        public string productCategory { get; set; }
        public string itemCondition { get; set; }
    }
}
