/*
Deployment script for Capstone Database

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Capstone Database"
:setvar DefaultFilePrefix "Capstone Database"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)] COLLATE SQL_Latin1_General_CP1_CI_AS
GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                PAGE_VERIFY NONE,
                DATE_CORRELATION_OPTIMIZATION OFF,
                DISABLE_BROKER,
                PARAMETERIZATION SIMPLE,
                SUPPLEMENTAL_LOGGING OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF,
        DB_CHAINING OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET HONOR_BROKER_PRIORITY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF),
                CONTAINMENT = NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF),
                MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = OFF,
                DELAYED_DURABILITY = DISABLED 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = ALL, DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_PLANS_PER_QUERY = 200, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), MAX_STORAGE_SIZE_MB = 100) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE = OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
    END


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
PRINT N'Creating [dbo].[Employee]...';


GO
CREATE TABLE [dbo].[Employee] (
    [employeId] INT          NOT NULL,
    [password]  VARCHAR (50) NOT NULL,
    [isManager] BIT          NOT NULL,
    [name]      VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([employeId] ASC)
);


GO
PRINT N'Creating [dbo].[Member]...';


GO
CREATE TABLE [dbo].[Member] (
    [memberId]    INT          NOT NULL,
    [username]    VARCHAR (50) NOT NULL,
    [name]        VARCHAR (50) NOT NULL,
    [password]    VARCHAR (50) NOT NULL,
    [isLibrarian] BIT          NOT NULL,
    [isBanned]    BIT          NOT NULL,
    PRIMARY KEY CLUSTERED ([memberId] ASC)
);


GO
PRINT N'Creating [dbo].[Product]...';


GO
CREATE TABLE [dbo].[Product] (
    [productId]   INT           NOT NULL,
    [name]        VARCHAR (50)  NOT NULL,
    [description] VARCHAR (300) NOT NULL,
    [type]        VARCHAR (50)  NOT NULL,
    PRIMARY KEY CLUSTERED ([productId] ASC)
);


GO
PRINT N'Creating [dbo].[Stock]...';


GO
CREATE TABLE [dbo].[Stock] (
    [stockId]   INT NOT NULL,
    [productId] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([stockId] ASC)
);


GO
PRINT N'Creating [dbo].[Rental]...';


GO
CREATE TABLE [dbo].[Rental] (
    [rentalId] INT NOT NULL,
    [stockId]  INT NOT NULL,
    [memberId] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([rentalId] ASC)
);


GO
PRINT N'Creating [dbo].[Return]...';


GO
CREATE TABLE [dbo].[Return] (
    [returnId]    INT          NOT NULL,
    [memberId]    INT          NOT NULL,
    [stockId]     INT          NOT NULL,
    [condition]   VARCHAR (50) NOT NULL,
    [description] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([returnId] ASC)
);


GO
PRINT N'Creating unnamed constraint on [dbo].[Employee]...';


GO
ALTER TABLE [dbo].[Employee]
    ADD DEFAULT 0 FOR [isManager];


GO
PRINT N'Creating unnamed constraint on [dbo].[Member]...';


GO
ALTER TABLE [dbo].[Member]
    ADD DEFAULT 0 FOR [isLibrarian];


GO
PRINT N'Creating unnamed constraint on [dbo].[Member]...';


GO
ALTER TABLE [dbo].[Member]
    ADD DEFAULT 0 FOR [isBanned];


GO
PRINT N'Creating [dbo].[FK_Stock_To_Product]...';


GO
ALTER TABLE [dbo].[Stock]
    ADD CONSTRAINT [FK_Stock_To_Product] FOREIGN KEY ([productId]) REFERENCES [dbo].[Product] ([productId]);


GO
PRINT N'Creating [dbo].[FK_Rental_Stock]...';


GO
ALTER TABLE [dbo].[Rental]
    ADD CONSTRAINT [FK_Rental_Stock] FOREIGN KEY ([stockId]) REFERENCES [dbo].[Stock] ([stockId]);


GO
PRINT N'Creating [dbo].[FK_Rental_Member]...';


GO
ALTER TABLE [dbo].[Rental]
    ADD CONSTRAINT [FK_Rental_Member] FOREIGN KEY ([memberId]) REFERENCES [dbo].[Member] ([memberId]);


GO
PRINT N'Creating [dbo].[FK_Return_Member]...';


GO
ALTER TABLE [dbo].[Return]
    ADD CONSTRAINT [FK_Return_Member] FOREIGN KEY ([memberId]) REFERENCES [dbo].[Member] ([memberId]);


GO
PRINT N'Creating [dbo].[FK_Return_Stock]...';


GO
ALTER TABLE [dbo].[Return]
    ADD CONSTRAINT [FK_Return_Stock] FOREIGN KEY ([stockId]) REFERENCES [dbo].[Stock] ([stockId]);


GO
-- Refactoring step to update target server with deployed transaction logs

IF OBJECT_ID(N'dbo.__RefactorLog') IS NULL
BEGIN
    CREATE TABLE [dbo].[__RefactorLog] (OperationKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY)
    EXEC sp_addextendedproperty N'microsoft_database_tools_support', N'refactoring log', N'schema', N'dbo', N'table', N'__RefactorLog'
END
GO
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '63bc430f-d245-4655-ba79-3c2092235663')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('63bc430f-d245-4655-ba79-3c2092235663')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'abc1ce72-2e2f-461b-b334-9b5d977b5ce2')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('abc1ce72-2e2f-461b-b334-9b5d977b5ce2')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '266821c7-f7f2-45c3-ad40-7478774a4fb0')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('266821c7-f7f2-45c3-ad40-7478774a4fb0')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '6a828a80-6182-463c-92e4-5738595be858')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('6a828a80-6182-463c-92e4-5738595be858')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '8a05902e-cbbd-4a96-8b87-9b1692e2c12f')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('8a05902e-cbbd-4a96-8b87-9b1692e2c12f')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'e5c47b97-fba4-4143-a863-001919a81b4b')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('e5c47b97-fba4-4143-a863-001919a81b4b')

GO

GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET MULTI_USER 
    WITH ROLLBACK IMMEDIATE;


GO
PRINT N'Update complete.';


GO
